apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: synergychat-web
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50